name: xMySQLBridge
main: com.gmail.xlifehd.xmysqlbridge.Main
version: 0.1.28
#TODO Add support for more economy plugins (add them to the softdepend list)
softdepend: [Essentials, Vault, SaneEconomy, Craftconomy3, Gringotts]
commands:
  xmbr:
    description: Test command
    usage: /xmbr